/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description List all active game sessions with connection info. Disabled in production.
         */
        get: operations["list_sessions_admin_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/elementals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Elementals
         * @description Get elementals available for player selection.
         *
         *     Returns only elementals that are enabled for the current game version.
         */
        get: operations["get_available_elementals_api_catalog_elementals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog/abilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Available Abilities
         * @description Get abilities available in the game.
         *
         *     Returns only abilities that are enabled for the current game version.
         */
        get: operations["get_available_abilities_api_catalog_abilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AvailableAbilitiesResponse
         * @description Response containing abilities available in game.
         */
        AvailableAbilitiesResponse: {
            /**
             * Abilities
             * @description Available abilities
             */
            abilities: components["schemas"]["AvailableAbility"][];
        };
        /**
         * AvailableAbility
         * @description Ability available in the game.
         */
        AvailableAbility: {
            /**
             * Id
             * @description Unique ability identifier
             */
            id: string;
            /**
             * Name
             * @description Display name
             */
            name: string;
            /**
             * Description
             * @description What the ability does
             */
            description: string;
            /** @description Presentation assets with resolved URLs */
            display_data: components["schemas"]["DisplayDataResponse"];
            /**
             * Can Target Friendly
             * @description Can target own blocks
             */
            can_target_friendly: boolean;
            /**
             * Cooldown Turns
             * @description Turns before reuse
             */
            cooldown_turns: number;
        };
        /**
         * AvailableElemental
         * @description Elemental available for player selection.
         */
        AvailableElemental: {
            /**
             * Id
             * @description Unique elemental identifier
             */
            id: string;
            /**
             * Name
             * @description Display name
             */
            name: string;
            /**
             * Description
             * @description Flavor text
             */
            description: string;
            /**
             * Color
             * @description Theme color (hex)
             */
            color: string;
            /**
             * Primary Ability Id
             * @description ID of primary ability
             */
            primary_ability_id: string;
            /** @description Presentation assets with resolved URLs */
            display_data: components["schemas"]["DisplayDataResponse"];
        };
        /**
         * AvailableElementalsResponse
         * @description Response containing elementals available for selection.
         */
        AvailableElementalsResponse: {
            /**
             * Elementals
             * @description Available elementals
             */
            elementals: components["schemas"]["AvailableElemental"][];
        };
        /**
         * DisplayDataResponse
         * @description Presentation data with resolved URLs for client consumption.
         */
        DisplayDataResponse: {
            /**
             * Icon Url
             * @description Full URL to icon asset
             */
            icon_url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_sessions_admin_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_available_elementals_api_catalog_elementals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableElementalsResponse"];
                };
            };
        };
    };
    get_available_abilities_api_catalog_abilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableAbilitiesResponse"];
                };
            };
        };
    };
}
