/**
 * Game data types derived from API schema.
 * 
 * These re-export from the generated OpenAPI types for convenience.
 * The source of truth is api.generated.ts (generated by generate_types.py).
 */

import type { components } from './api.generated'

// Re-export API types with friendlier names
export type DisplayData = components['schemas']['DisplayDataResponse']
export type AbilityData = components['schemas']['AvailableAbility']
export type ElementalData = components['schemas']['AvailableElemental']

// Composite type for full game catalog
export interface GameData {
  abilities: AbilityData[]
  elementals: ElementalData[]
}

// Elemental ID is a string - backend is source of truth for valid values
export type ElementalId = string
